### PR TITLE
Push all modifications to vmc++

### PR DESCRIPTION
**Pull request by francesco086**
Assigned to Jan

### CODE REVIEW

**Comment by Ithanil** [comment]
Oh quite a few files changed... I'll dig through it. 
Could you please explain in a few words the flaws of the previous library version and what you did differently here?

**Comment by Ithanil** [comment]
After fixing the run.sh I was able to run all 5 examples. BUT some results are inconsistent: 
Ex1 seems stable. 
In ex2 the optimization doesn't terminate in like 30-50% of cases.
Ex3 seems stable.
Ex4 is most serious: In like 50% of cases the optimal parameters and energy etc is nan . Also there seems to be some remaining debugging output from SR routines. 
Ex5 seems stable.

**Comment by Ithanil** [comment]
Removed all dSYM folders here from repo. Will also check the other repos and delete those.

And I guess you are aware of the valgrind output of debug/main , but just to be sure:
==26232== LEAK SUMMARY:
==26232==    definitely lost: 187 bytes in 31 blocks
==26232==    indirectly lost: 64 bytes in 4 blocks
==26232==      possibly lost: 0 bytes in 0 blocks
==26232==    still reachable: 0 bytes in 0 blocks
==26232==         suppressed: 0 bytes in 0 blocks
==26232== 
==26232== For counts of detected and suppressed errors, rerun with: -v
==26232== ERROR SUMMARY: 90 errors from 36 contexts (suppressed: 0 from 0)

**Review by Ithanil — CHANGES_REQUESTED** [review]
For feedback see my previous comments. I will approve merging, if questions are answered and examples are improved (if possible).

**Comment by francesco086** [comment]
To answer you first question: what did you change?
As I have written in Trello (comment), basically there's nothing really new, but I substantially changed the structure of the classes, especially the optimization ones.

About the not running examples, it could be that it is caused to the fact that you are not using the fixed NoisyFunMin library :) (which is in another issue in Trello)
Please try again using the fix_noisyfunmin branch in NoisyFunMin and let me know if it works.
I should be done with this soon too.

About the valgrind complaints: yes, I am aware of them, but after a long time trying to fix them I realizes that I am not able to. And since the code since to properly work.... I would leave it as it is. Of course if you are able to locate the problem it would be great!

**Review by Ithanil — APPROVED** [review]

**Comment by Ithanil** [comment]
OK, by using the other branch of NoisyFunMin most examples run consistently well now. Exception is ex2, which will rarely still stall while optimizing. But I think it is good for now. Merging.

**Pull request merged**
