### PR TITLE
Use simulated annealing to optimize a nnwf

### PR DESCRIPTION
**Pull request by francesco086**
Add an example to the VMC++ library, where an harmonic oscillator is solved with a NNwf.
Make the example run for different number of hidden units (2, 3, 5, 10) and of hidden layers (1, 2).

AC:
- the VMC++ library has a running example (ex7)
- variational energies are printed out for different sizes of the nn
- a plot (gnuplot) showing all the NNwf can be seen

### CODE REVIEW

**Comment by Ithanil** [comment]
Is it really necessary to add nearly 400 files and 70k+ lines of results to our repo? For an example? If we continue to do stuff like this the repo will become fat quickly :P
Well in this case it is too late anyway, unless we fiddle with the commits. So just leave it like that.

**Comment by francesco086** [comment]
mmm... you are right... the thing is that in fact such things should probably not be inside the examples.
Do you have any suggestion? I will think about it

**Comment by francesco086** [comment]
I moved the report to Resilio.
Is there anything else to change?

**Review by Ithanil — APPROVED** [review]
Except some optional "const" that could be added, all fine. Merge.

**Pull request merged**
